name: serpentine
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - numpy
  - matplotlib
  - heliopy
  - astropy
  - sunpy
  - ipywidgets
  - vtk
  - pip:
    - cdflib
    - k3d
