name: serpentine
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - numpy
  - matplotlib
  - heliopy
  - astropy
  - sunpy
  - ipywidgets
  - vtk
  - k3d=2.7.2
  - pip
  - pip:
    - cdflib
